version: '3'
services:
  php:
    build: .
    ports:
      - "7575:80"  # Exposing port 3000 for your PHP app
    depends_on:
      - mysql  # Make sure PHP waits for MySQL to be up before starting
    networks:
      - app_network

  mysql:
    image: mysql:5.7  # Using MySQL version 5.7
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set root password
      MYSQL_DATABASE: lost_and_found  # Default database to create
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
