version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lost_and_found
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
